Remove requirement for interop container
zendframework/zend-expressive-zendviewrenderer pull request #65
Opened 2019-05-20 22:47 UTC by Xerkus

zend-servicemanager ^3.4 allows plugin managers to use non-interop psr container.

This PR:
- bumps zend-servicemanager to ^3.4
- removes check in view helper plugin manager factory requiring psr container to also implement interop interface
- removes support for 2.* releases of zend-servicemanager

2019-05-20 22:53 UTC, Xerkus commented
@weierophinney this PR enables usage of zend-view with containers other than zend-servicemanager but it have to drop no longer maintained major version of dependency. Needs your sign-off.

2019-05-21 13:54 UTC, weierophinney requested changes
I think this makes sense. However, I'd bump to a new major version, as we're dropping support for an entire major version of releases of one of our dependencies.

Once we do, we'll need to make sure the skeleton application installs the new major version by default when this renderer is selected. (That can be a bugfix of minor release, however, as the skeleton is not a dependency of a project, but a starting point.)

Only changes I've suggested are for the changelog itself.

2019-05-21 13:54 UTC, weierophinney commented on CHANGELOG.md
> +  enables usage of non-interop psr containers with view helper plugin manager
"non-interop psr containers" feels like it is enabling usage of non-standard containers. I'd rephrase to something like "usage of any PSR-11 container with the view helper plugin manager".

2019-05-21 13:54 UTC, weierophinney commented on CHANGELOG.md
> +  removes support for 2.* series of zendframework/zend-servicemanager
```suggestion
  removes support for v2 releases of zendframework/zend-servicemanager
```

2019-06-04 04:23 UTC, merged